cha_coremapping:
	g++-13 -std=c++2b -g ./cha_coremapping.cpp ./logging.cpp -o ./cha_coremapping 

throttle:
	g++-13 -std=c++2b -g ./throttle.cpp -o ./throttle 
	
clean:
	rm -rf core2cha_layout cha_coremapping throttle